# Generated by Django 4.2.2 on 2023-06-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_carrito_venta_usuario_pedido_itemcarrito_favorito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
    ]
