# Generated by Django 4.2.1 on 2023-07-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0004_imagen_remove_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
